version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - ineffassign
    - misspell
    - gocritic
    - revive
  settings:
    errcheck:
      check-type-assertions: true
    misspell:
      locale: US
    revive:
      confidence: 0.8
      severity: warning

run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true
  allow-serial-runners: true

output:
  formats:
    text:
      print-issued-lines: true
      print-linter-name: true
      colors: true
